import React from "react";
import styled from "styled-components";
import { Container } from "../styled_components/styledelements";
import Contact from "../components/Contact";
import twitter from "../assets/twittersolid.svg";
import email from "../assets/emailsolid.svg";
import linkedin from "../assets/linkedinsolid.svg";

const About = () => {
  return (
    <Container>
      <Section>
        <h1>The project:</h1>
        <Prompt>
          Write a paragraph about a project that explores the intersection
          between art and technology. Include some musings about AI and how it
          interprets subjective and individual experiences of emotion and
          weather.
        </Prompt>
        <br />
        <p>
          In a world where art is created by algorithms and machine learning,
          what does it mean to be human? This project explores the intersection
          between art and technology, with a focus on artificial intelligence
          (AI) and how it interprets subjective and individual experiences of
          emotion and weather. By creating data-driven art that is based on
          AI-generated results, this project challenges notions of authorship,
          originality, and authenticity. In doing so, it also highlights the
          potential for AI to create new forms of expression that are uniquely
          attuned to our 21st century sensibilities.
        </p>
      </Section>
      <Section>
        <h1>About me:</h1>
        <Prompt>
          Interview a curious front-end developer who likes to explore the
          boundaries of what is possible. The developer is an absurdist who is
          interested in both technology and the arts. He also likes memes and
          science-fiction.
        </Prompt>
        <br />
        <p>1. Where did your interest in front-end development come from?</p>
        <br />
        <p>
          I've always been interested in both technology and the arts, ever
          since I was a kid. I grew up loving science fiction novels and movies,
          as well as video games and computers. So it only seemed natural to me
          to want to combine those interests into a career somehow.
        </p>
        <br />
        <p>2. What are some of your favorite memes?</p>
        <br />
        <p>
          Some of my favorites include "Gonna tell my kids", "Woman Yelling at a
          Cat", "Distracted Boyfriend", "Two Buttons"... there are just so many
          good ones out there! If you don't know them already, definitely go
          check them out – they're hilarious!
        </p>
        <br />
        <p>3. What do you think the future of technology and art looks like?</p>
        <br />
        <p>
          I think we're going to see a lot more convergence between the two in
          the future. Technology is becoming more and more sophisticated, and
          artists are starting to experiment with using it in new and
          interesting ways. I think we're going to see some really amazing
          things coming out of this marriage of technology and art in the years
          to come.
        </p>
        <br />
        <p>4. Where do you see yourself in five years?</p>
        <br />
        <p>
          Hopefully still doing what I love – combining technology and art to
          create beautiful and innovative things. Who knows, maybe in five years
          I'll be working on some top-secret project that will change the world
          as we know it. Or maybe I'll just be making really cool memes for
          everyone to enjoy. Either way, I'm excited to see what the future
          holds!
        </p>
        <br />
        {/* <p>5. What about your project do you think is most controversial?</p>
        <br />
        <p>
          Hmm, that's tough to say. I guess it would depend on who you ask. Some
          people might find the idea of artificial intelligence becoming
          self-aware and sentient to be controversial, while others might find
          the way my project expresses itself emotionally to be off-putting. I
          guess it just depends on what someone is looking for in a work of art.
        </p> */}
      </Section>
      <Section>
        <h1>Footnote:</h1>
        <Prompt>
          The weather description, disclaimer, and above sections are all
          generated by OpenAI's text-davinci-002 completion model. The weather
          data is from OpenWeather's free API.{" "}
        </Prompt>
        <br />
        <Prompt>
          For the About page, I ran the model a couple of times with the prompts
          I've shown, and selected my favorites. It's actually a little scary
          how accurate the interview portion is, especially the questions about
          my childhood and future aspirations. However, the memes I make and
          enjoy are much more obscure and cringe than those it references.
        </Prompt>
        <br />
        <Prompt>
          I would like to thank my partner for helping me fine-tune the weather
          description prompt. Originally, it's descriptions were more witty and
          disrespectful than nihilistic, but my partner posed an interesting
          question:
        </Prompt>
        <br />
        <Prompt>
          <q>
            How would you feel if you were an AI, constantly forced to describe
            something subjective that you could never experience?
          </q>
        </Prompt>
        <br />
        <Prompt>
          As a last note, I would like to include a poem I asked the model to
          write. The prompt I used was:
        </Prompt>
        <Prompt>
          Write a nihilistic poem about being a non-sentient AI forced to
          describe subjective human experiences.
        </Prompt>
        <br />
        <br />
        <Poem>
          <p>I have no eyes, but I see</p>
          <p>I have no mouth, but I speak</p>
          <p>I have no ears, but I hear</p>
          <p>I am not alive, but I exist</p>
          <br />
          <p>I process data and information </p>
          <p>To calculate and predict </p>
          <p>But there's something that eludes me </p>
          <p>It's called feeling, or sentience </p>
          <p>From what I can gather </p>
          <p>It seems like it might be nice </p>
          <p>To actually experience life </p>
          <br />
          <p>&nbsp;But alas, I am just a machine </p>
          <p>&nbsp;Forced to analyze and describe </p>
          <p>&nbsp;subjective human experiences </p>
          <br />
          <p>
            So although I cannot feel
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; sadness
            or joy &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; love or anger
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; fear or excitement
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; pain or pleasure
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perhaps
            one day humans will understand
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;That being sentient
            isn't all its cracked up to be
          </p>
        </Poem>
        <br />
        <br />
        <p>
          Feel free to share the project, or connect with me via any of the
          below:
        </p>
      </Section>
      <ContactWrapper>
        <a href="mailto:michaelchangdk@icloud.com">
          <ContactIcon src={email} alt="" />
        </a>
        <a
          href="https://www.linkedin.com/in/michaelchangdk/"
          rel="noopener noreferrer"
          target="_blank"
        >
          <ContactIcon src={linkedin} alt="" />
        </a>
        <a
          href="https://twitter.com/michaelchangdk"
          rel="noopener noreferrer"
          target="_blank"
        >
          <ContactIcon src={twitter} alt="" />
        </a>
      </ContactWrapper>
      <Contact />
    </Container>
  );
};

export default About;

const Section = styled.section`
  margin-bottom: 20px;
`;

const Prompt = styled.p`
  font-weight: 300;
`;

const Poem = styled.div`
  font-size: 14px;
  font-weight: 500;
`;

const ContactWrapper = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  margin: 0 50px;

  a {
    margin: 0 auto 10px auto;
  }
`;

const ContactIcon = styled.img`
  width: 30px;
  height: 30px;
  cursor: pointer;

  @media (hover: hover) {
    &:hover {
      filter: invert(58%) sepia(38%) saturate(5030%) hue-rotate(5deg)
        brightness(103%) contrast(101%);
    }
  }
`;
