import React from "react";
import styled from "styled-components";
import { Container } from "../styled_components/styledelements";
import Contact from "../components/Contact";

const About = () => {
  return (
    <Container>
      <Section>
        <h1>The project:</h1>
        <Prompt>
          Write a paragraph about a project that explores the intersection
          between art and technology. Include some musings about AI and how it
          interprets subjective and individual experiences of emotion and
          weather.
        </Prompt>
        <br />
        <p>
          In a world where art is created by algorithms and machine learning,
          what does it mean to be human? This project explores the intersection
          between art and technology, with a focus on artificial intelligence
          (AI) and how it interprets subjective and individual experiences of
          emotion and weather. By creating data-driven art that is based on
          AI-generated results, this project challenges notions of authorship,
          originality, and authenticity. In doing so, it also highlights the
          potential for AI to create new forms of expression that are uniquely
          attuned to our 21st century sensibilities.
        </p>
      </Section>
      <Section>
        <h1>About me:</h1>
        <Prompt>
          Interview a curious front-end developer who likes to explore the
          boundaries of what is possible. The developer is an absurdist who is
          interested in both technology and the arts. He also likes memes and
          science-fiction.
        </Prompt>
        <br />
        <p>1. Where did your interest in front-end development come from?</p>
        <br />
        <p>
          I've always been interested in both technology and the arts, ever
          since I was a kid. I grew up loving science fiction novels and movies,
          as well as video games and computers. So it only seemed natural to me
          to want to combine those interests into a career somehow.
        </p>
        <br />
        <p>2. What are some of your favorite memes?</p>
        <br />
        <p>
          Some of my favorites include "Gonna tell my kids", "Woman Yelling at a
          Cat", "Distracted Boyfriend", "Two Buttons"... there are just so many
          good ones out there! If you don't know them already, definitely go
          check them out – they're hilarious!
        </p>
        <br />
        <p>3. What do you think the future of technology and art looks like?</p>
        <br />
        <p>
          I think we're going to see a lot more convergence between the two in
          the future. Technology is becoming more and more sophisticated, and
          artists are starting to experiment with using it in new and
          interesting ways. I think we're going to see some really amazing
          things coming out of this marriage of technology and art in the years
          to come.
        </p>
        <br />
        <p>4. Where do you see yourself in five years?</p>
        <br />
        <p>
          Hopefully still doing what I love – combining technology and art to
          create beautiful and innovative things. Who knows, maybe in five years
          I'll be working on some top-secret project that will change the world
          as we know it. Or maybe I'll just be making really cool memes for
          everyone to enjoy. Either way, I'm excited to see what the future
          holds!
        </p>
      </Section>
      <Section>
        <h1>Footnote:</h1>
        <Prompt>
          The weather description, disclaimer, and above sections are all
          generated by OpenAI's text-davinci-002 completion model. The weather
          data is from OpenWeather's free API.{" "}
        </Prompt>
        <br />
        <Prompt>
          For the About page, I ran the model a couple of times with the prompts
          I've shown, and selected my favorites. It's actually a little scary
          how accurate the interview portion is, especially the questions about
          my childhood and future aspirations. However, the memes I make and
          enjoy are much more obscure and cringe than those it references.
        </Prompt>
        <br />
        <Prompt>
          I would like to thank my partner for helping me fine-tune the weather
          description prompt. Originally, it's descriptions were more witty and
          disrespectful than nihilistic, but my partner posed an interesting
          question:
        </Prompt>
        <br />
        <Prompt>
          <q>
            How would you feel if you were an AI, constantly forced to describe
            something subjective that you could never experience?
          </q>
        </Prompt>
        <br />
        <p>
          Feel free to share the project, contact me, or connect with me through
          any of the avenues below:
        </p>
      </Section>
      <Contact />
    </Container>
  );
};

export default About;

const Section = styled.section`
  margin-bottom: 20px;
`;

const Prompt = styled.p`
  font-weight: 300;
`;
